version: '2'
services:
  cms:
    build:
      context: ./docker-src/cms
    mem_limit: 2G
    volumes:
      - .:/var/www
    env_file: environment
    environment:
      - CONNECTBACK=on
    links:
      - db
      - memcache
    networks:
      - connector

  db:
    image: mariadb:latest
    mem_limit: 1G
    env_file: environment
    ports:
      - 3306:3306
    volumes:
      - ./docker-src/db/conf:/etc/mysql/conf.d
      - database:/var/lib/mysql
    networks:
      - connector

  memcache:
    image: memcached:latest
    mem_limit: 256M
    environment:
      - MEMCACHED_SERVER=memcached:11211
    ports:
      - 11211:11211
    networks:
      - connector

networks:
  connector:

volumes:
  database: {}
