module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  inline_entity_form: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  path: 0
  responsive_image: 0
  simple_gmap: 0
  social_media_links: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  skate: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
