targets:
  _blank:
    label: _blank
    description: 'Load in a new window'
  _self:
    label: _self
    description: 'Load in the same frame as it was clicked'
  _parent:
    label: _parent
    description: 'Load in the parent frameset'
  _top:
    label: _top
    description: 'Load in the full body of the window'
attributes:
  class:
    label: ''
    description: ''
  rel:
    label: Relationship
    description: ''
_core:
  default_config_hash: g0u8EMrBuZY0aCRVWkOX0_RHIjV5dnB2zDql0ND-54Q
